version: '3.8'
services:
  albatross1:
    image: archlinux:latest
    hostname: albratross
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.1.4
  albatross2:
    image: archlinux:latest
    hostname: albratross
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.2.4
  albatross3:
    image: archlinux:latest
    hostname: albratross
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.3.4
  albatross4:
    image: archlinux:latest
    hostname: albratross
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.4.4
  albatross5:
    image: archlinux:latest
    hostname: albratross
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.5.4
  orca1:
    image: rockylinux:8
    hostname: orca
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.1.5
  orca2:
    image: rockylinux:8
    hostname: orca
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.2.5
  orca3:
    image: rockylinux:8
    hostname: orca
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.3.5
  orca4:
    image: rockylinux:8
    hostname: orca
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.4.5
  orca5:
    image: rockylinux:8
    hostname: orca
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.5.5
  whale1:
    image: debian:latest
    hostname: whale
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.1.6
  whale2:
    image: debian:latest
    hostname: whale
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.2.6
  whale3:
    image: debian:latest
    hostname: whale
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.3.6
  whale4:
    image: debian:latest
    hostname: whale
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.4.6
  whale5:
    image: debian:latest
    hostname: whale
    volumes:
      - /home/skyz/:/app
    command: /app/rshell
    networks:
      lan:
        ipv4_address: 10.1.5.6
networks:
  lan:
    name: lan
    external: true
    #driver: bridge
    #ipam:
    #  config:
    #    - subnet: 10.0.0.0/8
    #      gateway: 10.255.255.254
